// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcxXNF21Cq7I8h-uUfMk5Pvzh2_yoWOgo',
    appId: '1:824990157472:web:b7794ef428b1e947f117c5',
    messagingSenderId: '824990157472',
    projectId: 'getsport-3d4dc',
    authDomain: 'getsport-3d4dc.firebaseapp.com',
    storageBucket: 'getsport-3d4dc.appspot.com',
    measurementId: 'G-G6M77EDF75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlrVO09SE5lT3aP-bU3wnCDdDuJ7fPBVw',
    appId: '1:824990157472:android:26e35a05f9272a51f117c5',
    messagingSenderId: '824990157472',
    projectId: 'getsport-3d4dc',
    storageBucket: 'getsport-3d4dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_G56Dvel7vMHQQBQIj41cJRukqVX_ZQ',
    appId: '1:824990157472:ios:6116423c9d9a1ce4f117c5',
    messagingSenderId: '824990157472',
    projectId: 'getsport-3d4dc',
    storageBucket: 'getsport-3d4dc.appspot.com',
    iosBundleId: 'com.example.getsport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF_G56Dvel7vMHQQBQIj41cJRukqVX_ZQ',
    appId: '1:824990157472:ios:6116423c9d9a1ce4f117c5',
    messagingSenderId: '824990157472',
    projectId: 'getsport-3d4dc',
    storageBucket: 'getsport-3d4dc.appspot.com',
    iosBundleId: 'com.example.getsport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcxXNF21Cq7I8h-uUfMk5Pvzh2_yoWOgo',
    appId: '1:824990157472:web:61b33c34a4e63770f117c5',
    messagingSenderId: '824990157472',
    projectId: 'getsport-3d4dc',
    authDomain: 'getsport-3d4dc.firebaseapp.com',
    storageBucket: 'getsport-3d4dc.appspot.com',
    measurementId: 'G-6NDH8584HP',
  );
}
